// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: libs/proto/payload.proto
// Protobuf C++ Version: 6.33.4

#ifndef libs_2fproto_2fpayload_2eproto_2epb_2eh
#define libs_2fproto_2fpayload_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_libs_2fproto_2fpayload_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_libs_2fproto_2fpayload_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_libs_2fproto_2fpayload_2eproto;
}  // extern "C"
namespace proto {
namespace v1 {
enum MissionReason : int;
extern const uint32_t MissionReason_internal_data_[];
enum MissionState : int;
extern const uint32_t MissionState_internal_data_[];
class HealthSample;
struct HealthSampleDefaultTypeInternal;
extern HealthSampleDefaultTypeInternal _HealthSample_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull HealthSample_class_data_;
class MissionUpdate;
struct MissionUpdateDefaultTypeInternal;
extern MissionUpdateDefaultTypeInternal _MissionUpdate_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull MissionUpdate_class_data_;
class Payload;
struct PayloadDefaultTypeInternal;
extern PayloadDefaultTypeInternal _Payload_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Payload_class_data_;
class PositionSample;
struct PositionSampleDefaultTypeInternal;
extern PositionSampleDefaultTypeInternal _PositionSample_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PositionSample_class_data_;
}  // namespace v1
}  // namespace proto
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::proto::v1::MissionReason_internal_data_>
    internal::EnumTraitsImpl::value<::proto::v1::MissionReason>;
template <>
internal::EnumTraitsT<::proto::v1::MissionState_internal_data_>
    internal::EnumTraitsImpl::value<::proto::v1::MissionState>;
}  // namespace protobuf
}  // namespace google

namespace proto {
namespace v1 {
enum MissionState : int {
  MISSION_STATE_UNSPECIFIED = 0,
  IDLE = 1,
  TAKEOFF = 2,
  PATROL = 3,
  RETURN_TO_HOME = 4,
  LANDED = 5,
  MissionState_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  MissionState_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t MissionState_internal_data_[];
inline constexpr MissionState MissionState_MIN =
    static_cast<MissionState>(0);
inline constexpr MissionState MissionState_MAX =
    static_cast<MissionState>(5);
inline bool MissionState_IsValid(int value) {
  return 0 <= value && value <= 5;
}
inline constexpr int MissionState_ARRAYSIZE = 5 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL MissionState_descriptor();
template <typename T>
const ::std::string& MissionState_Name(T value) {
  static_assert(::std::is_same<T, MissionState>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to MissionState_Name().");
  return MissionState_Name(static_cast<MissionState>(value));
}
template <>
inline const ::std::string& MissionState_Name(MissionState value) {
  return ::google::protobuf::internal::NameOfDenseEnum<MissionState_descriptor, 0, 5>(
      static_cast<int>(value));
}
inline bool MissionState_Parse(
    ::absl::string_view name, MissionState* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<MissionState>(MissionState_descriptor(), name,
                                           value);
}
enum MissionReason : int {
  MISSION_REASON_UNSPECIFIED = 0,
  STARTUP = 1,
  PATROL_STARTED = 2,
  LOW_BATTERY = 3,
  MANUAL_OVERRIDE = 4,
  MissionReason_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  MissionReason_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t MissionReason_internal_data_[];
inline constexpr MissionReason MissionReason_MIN =
    static_cast<MissionReason>(0);
inline constexpr MissionReason MissionReason_MAX =
    static_cast<MissionReason>(4);
inline bool MissionReason_IsValid(int value) {
  return 0 <= value && value <= 4;
}
inline constexpr int MissionReason_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL MissionReason_descriptor();
template <typename T>
const ::std::string& MissionReason_Name(T value) {
  static_assert(::std::is_same<T, MissionReason>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to MissionReason_Name().");
  return MissionReason_Name(static_cast<MissionReason>(value));
}
template <>
inline const ::std::string& MissionReason_Name(MissionReason value) {
  return ::google::protobuf::internal::NameOfDenseEnum<MissionReason_descriptor, 0, 4>(
      static_cast<int>(value));
}
inline bool MissionReason_Parse(
    ::absl::string_view name, MissionReason* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<MissionReason>(MissionReason_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class PositionSample final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.v1.PositionSample) */ {
 public:
  inline PositionSample() : PositionSample(nullptr) {}
  ~PositionSample() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PositionSample* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PositionSample));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PositionSample(::google::protobuf::internal::ConstantInitialized);

  inline PositionSample(const PositionSample& from) : PositionSample(nullptr, from) {}
  inline PositionSample(PositionSample&& from) noexcept
      : PositionSample(nullptr, ::std::move(from)) {}
  inline PositionSample& operator=(const PositionSample& from) {
    CopyFrom(from);
    return *this;
  }
  inline PositionSample& operator=(PositionSample&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PositionSample& default_instance() {
    return *reinterpret_cast<const PositionSample*>(
        &_PositionSample_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PositionSample& a, PositionSample& b) { a.Swap(&b); }
  inline void Swap(PositionSample* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PositionSample* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PositionSample* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PositionSample>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PositionSample& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PositionSample& from) { PositionSample::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PositionSample* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.v1.PositionSample"; }

  explicit PositionSample(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PositionSample(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PositionSample& from);
  PositionSample(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PositionSample&& from) noexcept
      : PositionSample(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLatitudeDegFieldNumber = 1,
    kLongitudeDegFieldNumber = 2,
    kAltitudeMFieldNumber = 3,
    kHeadingDegFieldNumber = 4,
    kSpeedMpsFieldNumber = 5,
  };
  // double latitude_deg = 1;
  void clear_latitude_deg() ;
  double latitude_deg() const;
  void set_latitude_deg(double value);

  private:
  double _internal_latitude_deg() const;
  void _internal_set_latitude_deg(double value);

  public:
  // double longitude_deg = 2;
  void clear_longitude_deg() ;
  double longitude_deg() const;
  void set_longitude_deg(double value);

  private:
  double _internal_longitude_deg() const;
  void _internal_set_longitude_deg(double value);

  public:
  // double altitude_m = 3;
  void clear_altitude_m() ;
  double altitude_m() const;
  void set_altitude_m(double value);

  private:
  double _internal_altitude_m() const;
  void _internal_set_altitude_m(double value);

  public:
  // double heading_deg = 4;
  void clear_heading_deg() ;
  double heading_deg() const;
  void set_heading_deg(double value);

  private:
  double _internal_heading_deg() const;
  void _internal_set_heading_deg(double value);

  public:
  // double speed_mps = 5;
  void clear_speed_mps() ;
  double speed_mps() const;
  void set_speed_mps(double value);

  private:
  double _internal_speed_mps() const;
  void _internal_set_speed_mps(double value);

  public:
  // @@protoc_insertion_point(class_scope:proto.v1.PositionSample)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PositionSample& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    double latitude_deg_;
    double longitude_deg_;
    double altitude_m_;
    double heading_deg_;
    double speed_mps_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_libs_2fproto_2fpayload_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PositionSample_class_data_;
// -------------------------------------------------------------------

class MissionUpdate final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.v1.MissionUpdate) */ {
 public:
  inline MissionUpdate() : MissionUpdate(nullptr) {}
  ~MissionUpdate() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MissionUpdate* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MissionUpdate));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MissionUpdate(::google::protobuf::internal::ConstantInitialized);

  inline MissionUpdate(const MissionUpdate& from) : MissionUpdate(nullptr, from) {}
  inline MissionUpdate(MissionUpdate&& from) noexcept
      : MissionUpdate(nullptr, ::std::move(from)) {}
  inline MissionUpdate& operator=(const MissionUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline MissionUpdate& operator=(MissionUpdate&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MissionUpdate& default_instance() {
    return *reinterpret_cast<const MissionUpdate*>(
        &_MissionUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(MissionUpdate& a, MissionUpdate& b) { a.Swap(&b); }
  inline void Swap(MissionUpdate* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MissionUpdate* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MissionUpdate* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MissionUpdate>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MissionUpdate& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MissionUpdate& from) { MissionUpdate::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MissionUpdate* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.v1.MissionUpdate"; }

  explicit MissionUpdate(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MissionUpdate(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MissionUpdate& from);
  MissionUpdate(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MissionUpdate&& from) noexcept
      : MissionUpdate(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStateFieldNumber = 1,
    kReasonFieldNumber = 2,
  };
  // .proto.v1.MissionState state = 1;
  void clear_state() ;
  ::proto::v1::MissionState state() const;
  void set_state(::proto::v1::MissionState value);

  private:
  ::proto::v1::MissionState _internal_state() const;
  void _internal_set_state(::proto::v1::MissionState value);

  public:
  // .proto.v1.MissionReason reason = 2;
  void clear_reason() ;
  ::proto::v1::MissionReason reason() const;
  void set_reason(::proto::v1::MissionReason value);

  private:
  ::proto::v1::MissionReason _internal_reason() const;
  void _internal_set_reason(::proto::v1::MissionReason value);

  public:
  // @@protoc_insertion_point(class_scope:proto.v1.MissionUpdate)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MissionUpdate& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int state_;
    int reason_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_libs_2fproto_2fpayload_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull MissionUpdate_class_data_;
// -------------------------------------------------------------------

class HealthSample final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.v1.HealthSample) */ {
 public:
  inline HealthSample() : HealthSample(nullptr) {}
  ~HealthSample() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HealthSample* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HealthSample));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HealthSample(::google::protobuf::internal::ConstantInitialized);

  inline HealthSample(const HealthSample& from) : HealthSample(nullptr, from) {}
  inline HealthSample(HealthSample&& from) noexcept
      : HealthSample(nullptr, ::std::move(from)) {}
  inline HealthSample& operator=(const HealthSample& from) {
    CopyFrom(from);
    return *this;
  }
  inline HealthSample& operator=(HealthSample&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HealthSample& default_instance() {
    return *reinterpret_cast<const HealthSample*>(
        &_HealthSample_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(HealthSample& a, HealthSample& b) { a.Swap(&b); }
  inline void Swap(HealthSample* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HealthSample* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HealthSample* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<HealthSample>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HealthSample& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const HealthSample& from) { HealthSample::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(HealthSample* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.v1.HealthSample"; }

  explicit HealthSample(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  HealthSample(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const HealthSample& from);
  HealthSample(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, HealthSample&& from) noexcept
      : HealthSample(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBatteryPctFieldNumber = 1,
    kLinkQualityPctFieldNumber = 2,
    kGpsFixTypeFieldNumber = 3,
  };
  // uint32 battery_pct = 1;
  void clear_battery_pct() ;
  ::uint32_t battery_pct() const;
  void set_battery_pct(::uint32_t value);

  private:
  ::uint32_t _internal_battery_pct() const;
  void _internal_set_battery_pct(::uint32_t value);

  public:
  // uint32 link_quality_pct = 2;
  void clear_link_quality_pct() ;
  ::uint32_t link_quality_pct() const;
  void set_link_quality_pct(::uint32_t value);

  private:
  ::uint32_t _internal_link_quality_pct() const;
  void _internal_set_link_quality_pct(::uint32_t value);

  public:
  // uint32 gps_fix_type = 3;
  void clear_gps_fix_type() ;
  ::uint32_t gps_fix_type() const;
  void set_gps_fix_type(::uint32_t value);

  private:
  ::uint32_t _internal_gps_fix_type() const;
  void _internal_set_gps_fix_type(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:proto.v1.HealthSample)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const HealthSample& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t battery_pct_;
    ::uint32_t link_quality_pct_;
    ::uint32_t gps_fix_type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_libs_2fproto_2fpayload_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull HealthSample_class_data_;
// -------------------------------------------------------------------

class Payload final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.v1.Payload) */ {
 public:
  inline Payload() : Payload(nullptr) {}
  ~Payload() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Payload* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Payload));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Payload(::google::protobuf::internal::ConstantInitialized);

  inline Payload(const Payload& from) : Payload(nullptr, from) {}
  inline Payload(Payload&& from) noexcept
      : Payload(nullptr, ::std::move(from)) {}
  inline Payload& operator=(const Payload& from) {
    CopyFrom(from);
    return *this;
  }
  inline Payload& operator=(Payload&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Payload& default_instance() {
    return *reinterpret_cast<const Payload*>(
        &_Payload_default_instance_);
  }
  enum SUnionCase {
    kPositionSample = 2,
    kHealthSample = 3,
    kMissionUpdate = 4,
    S_UNION_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(Payload& a, Payload& b) { a.Swap(&b); }
  inline void Swap(Payload* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Payload* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Payload* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Payload>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Payload& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Payload& from) { Payload::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Payload* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.v1.Payload"; }

  explicit Payload(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Payload(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Payload& from);
  Payload(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Payload&& from) noexcept
      : Payload(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kVersionFieldNumber = 1,
    kPositionSampleFieldNumber = 2,
    kHealthSampleFieldNumber = 3,
    kMissionUpdateFieldNumber = 4,
  };
  // uint32 version = 1;
  void clear_version() ;
  ::uint32_t version() const;
  void set_version(::uint32_t value);

  private:
  ::uint32_t _internal_version() const;
  void _internal_set_version(::uint32_t value);

  public:
  // .proto.v1.PositionSample position_sample = 2;
  bool has_position_sample() const;
  private:
  bool _internal_has_position_sample() const;

  public:
  void clear_position_sample() ;
  const ::proto::v1::PositionSample& position_sample() const;
  [[nodiscard]] ::proto::v1::PositionSample* PROTOBUF_NULLABLE release_position_sample();
  ::proto::v1::PositionSample* PROTOBUF_NONNULL mutable_position_sample();
  void set_allocated_position_sample(::proto::v1::PositionSample* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_position_sample(::proto::v1::PositionSample* PROTOBUF_NULLABLE value);
  ::proto::v1::PositionSample* PROTOBUF_NULLABLE unsafe_arena_release_position_sample();

  private:
  const ::proto::v1::PositionSample& _internal_position_sample() const;
  ::proto::v1::PositionSample* PROTOBUF_NONNULL _internal_mutable_position_sample();

  public:
  // .proto.v1.HealthSample health_sample = 3;
  bool has_health_sample() const;
  private:
  bool _internal_has_health_sample() const;

  public:
  void clear_health_sample() ;
  const ::proto::v1::HealthSample& health_sample() const;
  [[nodiscard]] ::proto::v1::HealthSample* PROTOBUF_NULLABLE release_health_sample();
  ::proto::v1::HealthSample* PROTOBUF_NONNULL mutable_health_sample();
  void set_allocated_health_sample(::proto::v1::HealthSample* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_health_sample(::proto::v1::HealthSample* PROTOBUF_NULLABLE value);
  ::proto::v1::HealthSample* PROTOBUF_NULLABLE unsafe_arena_release_health_sample();

  private:
  const ::proto::v1::HealthSample& _internal_health_sample() const;
  ::proto::v1::HealthSample* PROTOBUF_NONNULL _internal_mutable_health_sample();

  public:
  // .proto.v1.MissionUpdate mission_update = 4;
  bool has_mission_update() const;
  private:
  bool _internal_has_mission_update() const;

  public:
  void clear_mission_update() ;
  const ::proto::v1::MissionUpdate& mission_update() const;
  [[nodiscard]] ::proto::v1::MissionUpdate* PROTOBUF_NULLABLE release_mission_update();
  ::proto::v1::MissionUpdate* PROTOBUF_NONNULL mutable_mission_update();
  void set_allocated_mission_update(::proto::v1::MissionUpdate* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_mission_update(::proto::v1::MissionUpdate* PROTOBUF_NULLABLE value);
  ::proto::v1::MissionUpdate* PROTOBUF_NULLABLE unsafe_arena_release_mission_update();

  private:
  const ::proto::v1::MissionUpdate& _internal_mission_update() const;
  ::proto::v1::MissionUpdate* PROTOBUF_NONNULL _internal_mutable_mission_update();

  public:
  void clear_s_union();
  SUnionCase s_union_case() const;
  // @@protoc_insertion_point(class_scope:proto.v1.Payload)
 private:
  class _Internal;
  void set_has_position_sample();
  void set_has_health_sample();
  void set_has_mission_update();
  inline bool has_s_union() const;
  inline void clear_has_s_union();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 4,
                                   3, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Payload& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t version_;
    union SUnionUnion {
      constexpr SUnionUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE position_sample_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE health_sample_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE mission_update_;
    } s_union_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_libs_2fproto_2fpayload_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Payload_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PositionSample

// double latitude_deg = 1;
inline void PositionSample::clear_latitude_deg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.latitude_deg_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline double PositionSample::latitude_deg() const {
  // @@protoc_insertion_point(field_get:proto.v1.PositionSample.latitude_deg)
  return _internal_latitude_deg();
}
inline void PositionSample::set_latitude_deg(double value) {
  _internal_set_latitude_deg(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:proto.v1.PositionSample.latitude_deg)
}
inline double PositionSample::_internal_latitude_deg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.latitude_deg_;
}
inline void PositionSample::_internal_set_latitude_deg(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.latitude_deg_ = value;
}

// double longitude_deg = 2;
inline void PositionSample::clear_longitude_deg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.longitude_deg_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline double PositionSample::longitude_deg() const {
  // @@protoc_insertion_point(field_get:proto.v1.PositionSample.longitude_deg)
  return _internal_longitude_deg();
}
inline void PositionSample::set_longitude_deg(double value) {
  _internal_set_longitude_deg(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:proto.v1.PositionSample.longitude_deg)
}
inline double PositionSample::_internal_longitude_deg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.longitude_deg_;
}
inline void PositionSample::_internal_set_longitude_deg(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.longitude_deg_ = value;
}

// double altitude_m = 3;
inline void PositionSample::clear_altitude_m() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.altitude_m_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double PositionSample::altitude_m() const {
  // @@protoc_insertion_point(field_get:proto.v1.PositionSample.altitude_m)
  return _internal_altitude_m();
}
inline void PositionSample::set_altitude_m(double value) {
  _internal_set_altitude_m(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:proto.v1.PositionSample.altitude_m)
}
inline double PositionSample::_internal_altitude_m() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.altitude_m_;
}
inline void PositionSample::_internal_set_altitude_m(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.altitude_m_ = value;
}

// double heading_deg = 4;
inline void PositionSample::clear_heading_deg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heading_deg_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline double PositionSample::heading_deg() const {
  // @@protoc_insertion_point(field_get:proto.v1.PositionSample.heading_deg)
  return _internal_heading_deg();
}
inline void PositionSample::set_heading_deg(double value) {
  _internal_set_heading_deg(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:proto.v1.PositionSample.heading_deg)
}
inline double PositionSample::_internal_heading_deg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.heading_deg_;
}
inline void PositionSample::_internal_set_heading_deg(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heading_deg_ = value;
}

// double speed_mps = 5;
inline void PositionSample::clear_speed_mps() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.speed_mps_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline double PositionSample::speed_mps() const {
  // @@protoc_insertion_point(field_get:proto.v1.PositionSample.speed_mps)
  return _internal_speed_mps();
}
inline void PositionSample::set_speed_mps(double value) {
  _internal_set_speed_mps(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:proto.v1.PositionSample.speed_mps)
}
inline double PositionSample::_internal_speed_mps() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.speed_mps_;
}
inline void PositionSample::_internal_set_speed_mps(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.speed_mps_ = value;
}

// -------------------------------------------------------------------

// HealthSample

// uint32 battery_pct = 1;
inline void HealthSample::clear_battery_pct() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.battery_pct_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t HealthSample::battery_pct() const {
  // @@protoc_insertion_point(field_get:proto.v1.HealthSample.battery_pct)
  return _internal_battery_pct();
}
inline void HealthSample::set_battery_pct(::uint32_t value) {
  _internal_set_battery_pct(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:proto.v1.HealthSample.battery_pct)
}
inline ::uint32_t HealthSample::_internal_battery_pct() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.battery_pct_;
}
inline void HealthSample::_internal_set_battery_pct(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.battery_pct_ = value;
}

// uint32 link_quality_pct = 2;
inline void HealthSample::clear_link_quality_pct() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.link_quality_pct_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t HealthSample::link_quality_pct() const {
  // @@protoc_insertion_point(field_get:proto.v1.HealthSample.link_quality_pct)
  return _internal_link_quality_pct();
}
inline void HealthSample::set_link_quality_pct(::uint32_t value) {
  _internal_set_link_quality_pct(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:proto.v1.HealthSample.link_quality_pct)
}
inline ::uint32_t HealthSample::_internal_link_quality_pct() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.link_quality_pct_;
}
inline void HealthSample::_internal_set_link_quality_pct(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.link_quality_pct_ = value;
}

// uint32 gps_fix_type = 3;
inline void HealthSample::clear_gps_fix_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gps_fix_type_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t HealthSample::gps_fix_type() const {
  // @@protoc_insertion_point(field_get:proto.v1.HealthSample.gps_fix_type)
  return _internal_gps_fix_type();
}
inline void HealthSample::set_gps_fix_type(::uint32_t value) {
  _internal_set_gps_fix_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:proto.v1.HealthSample.gps_fix_type)
}
inline ::uint32_t HealthSample::_internal_gps_fix_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gps_fix_type_;
}
inline void HealthSample::_internal_set_gps_fix_type(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gps_fix_type_ = value;
}

// -------------------------------------------------------------------

// MissionUpdate

// .proto.v1.MissionState state = 1;
inline void MissionUpdate::clear_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::proto::v1::MissionState MissionUpdate::state() const {
  // @@protoc_insertion_point(field_get:proto.v1.MissionUpdate.state)
  return _internal_state();
}
inline void MissionUpdate::set_state(::proto::v1::MissionState value) {
  _internal_set_state(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:proto.v1.MissionUpdate.state)
}
inline ::proto::v1::MissionState MissionUpdate::_internal_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::proto::v1::MissionState>(_impl_.state_);
}
inline void MissionUpdate::_internal_set_state(::proto::v1::MissionState value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_ = value;
}

// .proto.v1.MissionReason reason = 2;
inline void MissionUpdate::clear_reason() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reason_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::proto::v1::MissionReason MissionUpdate::reason() const {
  // @@protoc_insertion_point(field_get:proto.v1.MissionUpdate.reason)
  return _internal_reason();
}
inline void MissionUpdate::set_reason(::proto::v1::MissionReason value) {
  _internal_set_reason(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:proto.v1.MissionUpdate.reason)
}
inline ::proto::v1::MissionReason MissionUpdate::_internal_reason() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::proto::v1::MissionReason>(_impl_.reason_);
}
inline void MissionUpdate::_internal_set_reason(::proto::v1::MissionReason value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reason_ = value;
}

// -------------------------------------------------------------------

// Payload

// uint32 version = 1;
inline void Payload::clear_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.version_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t Payload::version() const {
  // @@protoc_insertion_point(field_get:proto.v1.Payload.version)
  return _internal_version();
}
inline void Payload::set_version(::uint32_t value) {
  _internal_set_version(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:proto.v1.Payload.version)
}
inline ::uint32_t Payload::_internal_version() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.version_;
}
inline void Payload::_internal_set_version(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.version_ = value;
}

// .proto.v1.PositionSample position_sample = 2;
inline bool Payload::has_position_sample() const {
  return s_union_case() == kPositionSample;
}
inline bool Payload::_internal_has_position_sample() const {
  return s_union_case() == kPositionSample;
}
inline void Payload::set_has_position_sample() {
  _impl_._oneof_case_[0] = kPositionSample;
}
inline void Payload::clear_position_sample() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (s_union_case() == kPositionSample) {
    if (GetArena() == nullptr) {
      delete _impl_.s_union_.position_sample_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.s_union_.position_sample_);
    }
    clear_has_s_union();
  }
}
inline ::proto::v1::PositionSample* PROTOBUF_NULLABLE Payload::release_position_sample() {
  // @@protoc_insertion_point(field_release:proto.v1.Payload.position_sample)
  if (s_union_case() == kPositionSample) {
    clear_has_s_union();
    auto* temp = reinterpret_cast<::proto::v1::PositionSample*>(_impl_.s_union_.position_sample_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.s_union_.position_sample_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::proto::v1::PositionSample& Payload::_internal_position_sample() const {
  return s_union_case() == kPositionSample ? static_cast<const ::proto::v1::PositionSample&>(*reinterpret_cast<::proto::v1::PositionSample*>(_impl_.s_union_.position_sample_))
                     : reinterpret_cast<const ::proto::v1::PositionSample&>(::proto::v1::_PositionSample_default_instance_);
}
inline const ::proto::v1::PositionSample& Payload::position_sample() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.v1.Payload.position_sample)
  return _internal_position_sample();
}
inline ::proto::v1::PositionSample* PROTOBUF_NULLABLE Payload::unsafe_arena_release_position_sample() {
  // @@protoc_insertion_point(field_unsafe_arena_release:proto.v1.Payload.position_sample)
  if (s_union_case() == kPositionSample) {
    clear_has_s_union();
    auto* temp = reinterpret_cast<::proto::v1::PositionSample*>(_impl_.s_union_.position_sample_);
    _impl_.s_union_.position_sample_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Payload::unsafe_arena_set_allocated_position_sample(
    ::proto::v1::PositionSample* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_s_union();
  if (value) {
    set_has_position_sample();
    _impl_.s_union_.position_sample_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.v1.Payload.position_sample)
}
inline ::proto::v1::PositionSample* PROTOBUF_NONNULL Payload::_internal_mutable_position_sample() {
  if (s_union_case() != kPositionSample) {
    clear_s_union();
    set_has_position_sample();
    _impl_.s_union_.position_sample_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::proto::v1::PositionSample>(GetArena()));
  }
  return reinterpret_cast<::proto::v1::PositionSample*>(_impl_.s_union_.position_sample_);
}
inline ::proto::v1::PositionSample* PROTOBUF_NONNULL Payload::mutable_position_sample()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::proto::v1::PositionSample* _msg = _internal_mutable_position_sample();
  // @@protoc_insertion_point(field_mutable:proto.v1.Payload.position_sample)
  return _msg;
}

// .proto.v1.HealthSample health_sample = 3;
inline bool Payload::has_health_sample() const {
  return s_union_case() == kHealthSample;
}
inline bool Payload::_internal_has_health_sample() const {
  return s_union_case() == kHealthSample;
}
inline void Payload::set_has_health_sample() {
  _impl_._oneof_case_[0] = kHealthSample;
}
inline void Payload::clear_health_sample() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (s_union_case() == kHealthSample) {
    if (GetArena() == nullptr) {
      delete _impl_.s_union_.health_sample_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.s_union_.health_sample_);
    }
    clear_has_s_union();
  }
}
inline ::proto::v1::HealthSample* PROTOBUF_NULLABLE Payload::release_health_sample() {
  // @@protoc_insertion_point(field_release:proto.v1.Payload.health_sample)
  if (s_union_case() == kHealthSample) {
    clear_has_s_union();
    auto* temp = reinterpret_cast<::proto::v1::HealthSample*>(_impl_.s_union_.health_sample_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.s_union_.health_sample_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::proto::v1::HealthSample& Payload::_internal_health_sample() const {
  return s_union_case() == kHealthSample ? static_cast<const ::proto::v1::HealthSample&>(*reinterpret_cast<::proto::v1::HealthSample*>(_impl_.s_union_.health_sample_))
                     : reinterpret_cast<const ::proto::v1::HealthSample&>(::proto::v1::_HealthSample_default_instance_);
}
inline const ::proto::v1::HealthSample& Payload::health_sample() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.v1.Payload.health_sample)
  return _internal_health_sample();
}
inline ::proto::v1::HealthSample* PROTOBUF_NULLABLE Payload::unsafe_arena_release_health_sample() {
  // @@protoc_insertion_point(field_unsafe_arena_release:proto.v1.Payload.health_sample)
  if (s_union_case() == kHealthSample) {
    clear_has_s_union();
    auto* temp = reinterpret_cast<::proto::v1::HealthSample*>(_impl_.s_union_.health_sample_);
    _impl_.s_union_.health_sample_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Payload::unsafe_arena_set_allocated_health_sample(
    ::proto::v1::HealthSample* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_s_union();
  if (value) {
    set_has_health_sample();
    _impl_.s_union_.health_sample_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.v1.Payload.health_sample)
}
inline ::proto::v1::HealthSample* PROTOBUF_NONNULL Payload::_internal_mutable_health_sample() {
  if (s_union_case() != kHealthSample) {
    clear_s_union();
    set_has_health_sample();
    _impl_.s_union_.health_sample_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::proto::v1::HealthSample>(GetArena()));
  }
  return reinterpret_cast<::proto::v1::HealthSample*>(_impl_.s_union_.health_sample_);
}
inline ::proto::v1::HealthSample* PROTOBUF_NONNULL Payload::mutable_health_sample()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::proto::v1::HealthSample* _msg = _internal_mutable_health_sample();
  // @@protoc_insertion_point(field_mutable:proto.v1.Payload.health_sample)
  return _msg;
}

// .proto.v1.MissionUpdate mission_update = 4;
inline bool Payload::has_mission_update() const {
  return s_union_case() == kMissionUpdate;
}
inline bool Payload::_internal_has_mission_update() const {
  return s_union_case() == kMissionUpdate;
}
inline void Payload::set_has_mission_update() {
  _impl_._oneof_case_[0] = kMissionUpdate;
}
inline void Payload::clear_mission_update() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (s_union_case() == kMissionUpdate) {
    if (GetArena() == nullptr) {
      delete _impl_.s_union_.mission_update_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.s_union_.mission_update_);
    }
    clear_has_s_union();
  }
}
inline ::proto::v1::MissionUpdate* PROTOBUF_NULLABLE Payload::release_mission_update() {
  // @@protoc_insertion_point(field_release:proto.v1.Payload.mission_update)
  if (s_union_case() == kMissionUpdate) {
    clear_has_s_union();
    auto* temp = reinterpret_cast<::proto::v1::MissionUpdate*>(_impl_.s_union_.mission_update_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.s_union_.mission_update_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::proto::v1::MissionUpdate& Payload::_internal_mission_update() const {
  return s_union_case() == kMissionUpdate ? static_cast<const ::proto::v1::MissionUpdate&>(*reinterpret_cast<::proto::v1::MissionUpdate*>(_impl_.s_union_.mission_update_))
                     : reinterpret_cast<const ::proto::v1::MissionUpdate&>(::proto::v1::_MissionUpdate_default_instance_);
}
inline const ::proto::v1::MissionUpdate& Payload::mission_update() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.v1.Payload.mission_update)
  return _internal_mission_update();
}
inline ::proto::v1::MissionUpdate* PROTOBUF_NULLABLE Payload::unsafe_arena_release_mission_update() {
  // @@protoc_insertion_point(field_unsafe_arena_release:proto.v1.Payload.mission_update)
  if (s_union_case() == kMissionUpdate) {
    clear_has_s_union();
    auto* temp = reinterpret_cast<::proto::v1::MissionUpdate*>(_impl_.s_union_.mission_update_);
    _impl_.s_union_.mission_update_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Payload::unsafe_arena_set_allocated_mission_update(
    ::proto::v1::MissionUpdate* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_s_union();
  if (value) {
    set_has_mission_update();
    _impl_.s_union_.mission_update_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.v1.Payload.mission_update)
}
inline ::proto::v1::MissionUpdate* PROTOBUF_NONNULL Payload::_internal_mutable_mission_update() {
  if (s_union_case() != kMissionUpdate) {
    clear_s_union();
    set_has_mission_update();
    _impl_.s_union_.mission_update_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::proto::v1::MissionUpdate>(GetArena()));
  }
  return reinterpret_cast<::proto::v1::MissionUpdate*>(_impl_.s_union_.mission_update_);
}
inline ::proto::v1::MissionUpdate* PROTOBUF_NONNULL Payload::mutable_mission_update()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::proto::v1::MissionUpdate* _msg = _internal_mutable_mission_update();
  // @@protoc_insertion_point(field_mutable:proto.v1.Payload.mission_update)
  return _msg;
}

inline bool Payload::has_s_union() const {
  return s_union_case() != S_UNION_NOT_SET;
}
inline void Payload::clear_has_s_union() {
  _impl_._oneof_case_[0] = S_UNION_NOT_SET;
}
inline Payload::SUnionCase Payload::s_union_case() const {
  return Payload::SUnionCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace proto


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::proto::v1::MissionState> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::proto::v1::MissionState>() {
  return ::proto::v1::MissionState_descriptor();
}
template <>
struct is_proto_enum<::proto::v1::MissionReason> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::proto::v1::MissionReason>() {
  return ::proto::v1::MissionReason_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // libs_2fproto_2fpayload_2eproto_2epb_2eh
