// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: libs/proto/device_event.proto
// Protobuf C++ Version: 6.33.4

#include "proto/device_event.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace gundam {
namespace v1 {

inline constexpr PositionSample::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        latitude_deg_{0},
        longitude_deg_{0},
        altitude_m_{0},
        heading_deg_{0},
        speed_mps_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PositionSample::PositionSample(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PositionSample_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PositionSampleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PositionSampleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PositionSampleDefaultTypeInternal() {}
  union {
    PositionSample _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PositionSampleDefaultTypeInternal _PositionSample_default_instance_;

inline constexpr MissionUpdate::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        state_{static_cast< ::gundam::v1::MissionState >(0)},
        reason_{static_cast< ::gundam::v1::MissionReason >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR MissionUpdate::MissionUpdate(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(MissionUpdate_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MissionUpdateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MissionUpdateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MissionUpdateDefaultTypeInternal() {}
  union {
    MissionUpdate _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MissionUpdateDefaultTypeInternal _MissionUpdate_default_instance_;

inline constexpr HealthSample::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        battery_pct_{0u},
        link_quality_pct_{0u},
        gps_fix_type_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR HealthSample::HealthSample(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(HealthSample_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct HealthSampleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HealthSampleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HealthSampleDefaultTypeInternal() {}
  union {
    HealthSample _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HealthSampleDefaultTypeInternal _HealthSample_default_instance_;

inline constexpr DeviceEvent::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        event_id_{::uint64_t{0u}},
        device_id_{::uint64_t{0u}},
        timestamp_unix_ms_{::uint64_t{0u}},
        type_{static_cast< ::gundam::v1::EventType >(0)},
        payload_version_{0u},
        payload_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR DeviceEvent::DeviceEvent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(DeviceEvent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DeviceEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DeviceEventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DeviceEventDefaultTypeInternal() {}
  union {
    DeviceEvent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DeviceEventDefaultTypeInternal _DeviceEvent_default_instance_;
}  // namespace v1
}  // namespace gundam
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_libs_2fproto_2fdevice_5fevent_2eproto[3];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_libs_2fproto_2fdevice_5fevent_2eproto = nullptr;
const ::uint32_t
    TableStruct_libs_2fproto_2fdevice_5fevent_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::gundam::v1::PositionSample, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::gundam::v1::PositionSample, _impl_.latitude_deg_),
        PROTOBUF_FIELD_OFFSET(::gundam::v1::PositionSample, _impl_.longitude_deg_),
        PROTOBUF_FIELD_OFFSET(::gundam::v1::PositionSample, _impl_.altitude_m_),
        PROTOBUF_FIELD_OFFSET(::gundam::v1::PositionSample, _impl_.heading_deg_),
        PROTOBUF_FIELD_OFFSET(::gundam::v1::PositionSample, _impl_.speed_mps_),
        0,
        1,
        2,
        3,
        4,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::gundam::v1::HealthSample, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::gundam::v1::HealthSample, _impl_.battery_pct_),
        PROTOBUF_FIELD_OFFSET(::gundam::v1::HealthSample, _impl_.link_quality_pct_),
        PROTOBUF_FIELD_OFFSET(::gundam::v1::HealthSample, _impl_.gps_fix_type_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::gundam::v1::MissionUpdate, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::gundam::v1::MissionUpdate, _impl_.state_),
        PROTOBUF_FIELD_OFFSET(::gundam::v1::MissionUpdate, _impl_.reason_),
        0,
        1,
        0x085, // bitmap
        PROTOBUF_FIELD_OFFSET(::gundam::v1::DeviceEvent, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::gundam::v1::DeviceEvent, _impl_._oneof_case_[0]),
        13, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::gundam::v1::DeviceEvent, _impl_.event_id_),
        PROTOBUF_FIELD_OFFSET(::gundam::v1::DeviceEvent, _impl_.device_id_),
        PROTOBUF_FIELD_OFFSET(::gundam::v1::DeviceEvent, _impl_.timestamp_unix_ms_),
        PROTOBUF_FIELD_OFFSET(::gundam::v1::DeviceEvent, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::gundam::v1::DeviceEvent, _impl_.payload_version_),
        PROTOBUF_FIELD_OFFSET(::gundam::v1::DeviceEvent, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::gundam::v1::DeviceEvent, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::gundam::v1::DeviceEvent, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::gundam::v1::DeviceEvent, _impl_.payload_),
        0,
        1,
        2,
        3,
        4,
        ~0u,
        ~0u,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::gundam::v1::PositionSample)},
        {13, sizeof(::gundam::v1::HealthSample)},
        {22, sizeof(::gundam::v1::MissionUpdate)},
        {29, sizeof(::gundam::v1::DeviceEvent)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::gundam::v1::_PositionSample_default_instance_._instance,
    &::gundam::v1::_HealthSample_default_instance_._instance,
    &::gundam::v1::_MissionUpdate_default_instance_._instance,
    &::gundam::v1::_DeviceEvent_default_instance_._instance,
};
const char descriptor_table_protodef_libs_2fproto_2fdevice_5fevent_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\035libs/proto/device_event.proto\022\tgundam."
    "v1\"y\n\016PositionSample\022\024\n\014latitude_deg\030\001 \001"
    "(\001\022\025\n\rlongitude_deg\030\002 \001(\001\022\022\n\naltitude_m\030"
    "\003 \001(\001\022\023\n\013heading_deg\030\004 \001(\001\022\021\n\tspeed_mps\030"
    "\005 \001(\001\"S\n\014HealthSample\022\023\n\013battery_pct\030\001 \001"
    "(\r\022\030\n\020link_quality_pct\030\002 \001(\r\022\024\n\014gps_fix_"
    "type\030\003 \001(\r\"a\n\rMissionUpdate\022&\n\005state\030\001 \001"
    "(\0162\027.gundam.v1.MissionState\022(\n\006reason\030\002 "
    "\001(\0162\030.gundam.v1.MissionReason\"\261\002\n\013Device"
    "Event\022\020\n\010event_id\030\001 \001(\004\022\021\n\tdevice_id\030\002 \001"
    "(\004\022\031\n\021timestamp_unix_ms\030\003 \001(\004\022\"\n\004type\030\004 "
    "\001(\0162\024.gundam.v1.EventType\022\027\n\017payload_ver"
    "sion\030\005 \001(\r\0224\n\017position_sample\030\n \001(\0132\031.gu"
    "ndam.v1.PositionSampleH\000\0220\n\rhealth_sampl"
    "e\030\013 \001(\0132\027.gundam.v1.HealthSampleH\000\0222\n\016mi"
    "ssion_update\030\014 \001(\0132\030.gundam.v1.MissionUp"
    "dateH\000B\t\n\007payload*X\n\tEventType\022\017\n\013UNSPEC"
    "IFIED\020\000\022\023\n\017POSITION_SAMPLE\020\001\022\021\n\rHEALTH_S"
    "AMPLE\020\002\022\022\n\016MISSION_UPDATE\020\003*p\n\014MissionSt"
    "ate\022\035\n\031MISSION_STATE_UNSPECIFIED\020\000\022\010\n\004ID"
    "LE\020\001\022\013\n\007TAKEOFF\020\002\022\n\n\006PATROL\020\003\022\022\n\016RETURN_"
    "TO_HOME\020\004\022\n\n\006LANDED\020\005*v\n\rMissionReason\022\036"
    "\n\032MISSION_REASON_UNSPECIFIED\020\000\022\013\n\007STARTU"
    "P\020\001\022\022\n\016PATROL_STARTED\020\002\022\017\n\013LOW_BATTERY\020\003"
    "\022\023\n\017MANUAL_OVERRIDE\020\004b\006proto3"
};
static ::absl::once_flag descriptor_table_libs_2fproto_2fdevice_5fevent_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_libs_2fproto_2fdevice_5fevent_2eproto = {
    false,
    false,
    989,
    descriptor_table_protodef_libs_2fproto_2fdevice_5fevent_2eproto,
    "libs/proto/device_event.proto",
    &descriptor_table_libs_2fproto_2fdevice_5fevent_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_libs_2fproto_2fdevice_5fevent_2eproto::offsets,
    file_level_enum_descriptors_libs_2fproto_2fdevice_5fevent_2eproto,
    file_level_service_descriptors_libs_2fproto_2fdevice_5fevent_2eproto,
};
namespace gundam {
namespace v1 {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL EventType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_libs_2fproto_2fdevice_5fevent_2eproto);
  return file_level_enum_descriptors_libs_2fproto_2fdevice_5fevent_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t EventType_internal_data_[] = {
    262144u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL MissionState_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_libs_2fproto_2fdevice_5fevent_2eproto);
  return file_level_enum_descriptors_libs_2fproto_2fdevice_5fevent_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t MissionState_internal_data_[] = {
    393216u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL MissionReason_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_libs_2fproto_2fdevice_5fevent_2eproto);
  return file_level_enum_descriptors_libs_2fproto_2fdevice_5fevent_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t MissionReason_internal_data_[] = {
    327680u, 0u, };
// ===================================================================

class PositionSample::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PositionSample>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PositionSample, _impl_._has_bits_);
};

PositionSample::PositionSample(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PositionSample_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gundam.v1.PositionSample)
}
PositionSample::PositionSample(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PositionSample& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PositionSample_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE PositionSample::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void PositionSample::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, latitude_deg_),
           0,
           offsetof(Impl_, speed_mps_) -
               offsetof(Impl_, latitude_deg_) +
               sizeof(Impl_::speed_mps_));
}
PositionSample::~PositionSample() {
  // @@protoc_insertion_point(destructor:gundam.v1.PositionSample)
  SharedDtor(*this);
}
inline void PositionSample::SharedDtor(MessageLite& self) {
  PositionSample& this_ = static_cast<PositionSample&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PositionSample::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PositionSample(arena);
}
constexpr auto PositionSample::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PositionSample),
                                            alignof(PositionSample));
}
constexpr auto PositionSample::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PositionSample_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PositionSample::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PositionSample>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PositionSample::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PositionSample>(), &PositionSample::ByteSizeLong,
              &PositionSample::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PositionSample, _impl_._cached_size_),
          false,
      },
      &PositionSample::kDescriptorMethods,
      &descriptor_table_libs_2fproto_2fdevice_5fevent_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PositionSample_class_data_ =
        PositionSample::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PositionSample::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PositionSample_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PositionSample_class_data_.tc_table);
  return PositionSample_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2>
PositionSample::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PositionSample, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PositionSample_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::gundam::v1::PositionSample>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // double latitude_deg = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 0, 0,
      PROTOBUF_FIELD_OFFSET(PositionSample, _impl_.latitude_deg_)}},
    // double longitude_deg = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 1, 0,
      PROTOBUF_FIELD_OFFSET(PositionSample, _impl_.longitude_deg_)}},
    // double altitude_m = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 2, 0,
      PROTOBUF_FIELD_OFFSET(PositionSample, _impl_.altitude_m_)}},
    // double heading_deg = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 3, 0,
      PROTOBUF_FIELD_OFFSET(PositionSample, _impl_.heading_deg_)}},
    // double speed_mps = 5;
    {::_pbi::TcParser::FastF64S1,
     {41, 4, 0,
      PROTOBUF_FIELD_OFFSET(PositionSample, _impl_.speed_mps_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // double latitude_deg = 1;
    {PROTOBUF_FIELD_OFFSET(PositionSample, _impl_.latitude_deg_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double longitude_deg = 2;
    {PROTOBUF_FIELD_OFFSET(PositionSample, _impl_.longitude_deg_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double altitude_m = 3;
    {PROTOBUF_FIELD_OFFSET(PositionSample, _impl_.altitude_m_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double heading_deg = 4;
    {PROTOBUF_FIELD_OFFSET(PositionSample, _impl_.heading_deg_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double speed_mps = 5;
    {PROTOBUF_FIELD_OFFSET(PositionSample, _impl_.speed_mps_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PositionSample::Clear() {
// @@protoc_insertion_point(message_clear_start:gundam.v1.PositionSample)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    ::memset(&_impl_.latitude_deg_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.speed_mps_) -
        reinterpret_cast<char*>(&_impl_.latitude_deg_)) + sizeof(_impl_.speed_mps_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PositionSample::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PositionSample& this_ = static_cast<const PositionSample&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PositionSample::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PositionSample& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:gundam.v1.PositionSample)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // double latitude_deg = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_latitude_deg()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          1, this_._internal_latitude_deg(), target);
    }
  }

  // double longitude_deg = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_longitude_deg()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          2, this_._internal_longitude_deg(), target);
    }
  }

  // double altitude_m = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_altitude_m()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          3, this_._internal_altitude_m(), target);
    }
  }

  // double heading_deg = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_heading_deg()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          4, this_._internal_heading_deg(), target);
    }
  }

  // double speed_mps = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_speed_mps()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          5, this_._internal_speed_mps(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gundam.v1.PositionSample)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PositionSample::ByteSizeLong(const MessageLite& base) {
  const PositionSample& this_ = static_cast<const PositionSample&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PositionSample::ByteSizeLong() const {
  const PositionSample& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:gundam.v1.PositionSample)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // double latitude_deg = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_latitude_deg()) != 0) {
        total_size += 9;
      }
    }
    // double longitude_deg = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_longitude_deg()) != 0) {
        total_size += 9;
      }
    }
    // double altitude_m = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_altitude_m()) != 0) {
        total_size += 9;
      }
    }
    // double heading_deg = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_heading_deg()) != 0) {
        total_size += 9;
      }
    }
    // double speed_mps = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_speed_mps()) != 0) {
        total_size += 9;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PositionSample::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PositionSample*>(&to_msg);
  auto& from = static_cast<const PositionSample&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:gundam.v1.PositionSample)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_latitude_deg()) != 0) {
        _this->_impl_.latitude_deg_ = from._impl_.latitude_deg_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_longitude_deg()) != 0) {
        _this->_impl_.longitude_deg_ = from._impl_.longitude_deg_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_altitude_m()) != 0) {
        _this->_impl_.altitude_m_ = from._impl_.altitude_m_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_heading_deg()) != 0) {
        _this->_impl_.heading_deg_ = from._impl_.heading_deg_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_speed_mps()) != 0) {
        _this->_impl_.speed_mps_ = from._impl_.speed_mps_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PositionSample::CopyFrom(const PositionSample& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:gundam.v1.PositionSample)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PositionSample::InternalSwap(PositionSample* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PositionSample, _impl_.speed_mps_)
      + sizeof(PositionSample::_impl_.speed_mps_)
      - PROTOBUF_FIELD_OFFSET(PositionSample, _impl_.latitude_deg_)>(
          reinterpret_cast<char*>(&_impl_.latitude_deg_),
          reinterpret_cast<char*>(&other->_impl_.latitude_deg_));
}

::google::protobuf::Metadata PositionSample::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class HealthSample::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<HealthSample>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(HealthSample, _impl_._has_bits_);
};

HealthSample::HealthSample(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HealthSample_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gundam.v1.HealthSample)
}
HealthSample::HealthSample(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const HealthSample& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HealthSample_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE HealthSample::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void HealthSample::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, battery_pct_),
           0,
           offsetof(Impl_, gps_fix_type_) -
               offsetof(Impl_, battery_pct_) +
               sizeof(Impl_::gps_fix_type_));
}
HealthSample::~HealthSample() {
  // @@protoc_insertion_point(destructor:gundam.v1.HealthSample)
  SharedDtor(*this);
}
inline void HealthSample::SharedDtor(MessageLite& self) {
  HealthSample& this_ = static_cast<HealthSample&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL HealthSample::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) HealthSample(arena);
}
constexpr auto HealthSample::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(HealthSample),
                                            alignof(HealthSample));
}
constexpr auto HealthSample::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_HealthSample_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &HealthSample::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<HealthSample>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &HealthSample::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<HealthSample>(), &HealthSample::ByteSizeLong,
              &HealthSample::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(HealthSample, _impl_._cached_size_),
          false,
      },
      &HealthSample::kDescriptorMethods,
      &descriptor_table_libs_2fproto_2fdevice_5fevent_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull HealthSample_class_data_ =
        HealthSample::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
HealthSample::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&HealthSample_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(HealthSample_class_data_.tc_table);
  return HealthSample_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
HealthSample::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(HealthSample, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    HealthSample_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::gundam::v1::HealthSample>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 battery_pct = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(HealthSample, _impl_.battery_pct_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(HealthSample, _impl_.battery_pct_)}},
    // uint32 link_quality_pct = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(HealthSample, _impl_.link_quality_pct_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(HealthSample, _impl_.link_quality_pct_)}},
    // uint32 gps_fix_type = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(HealthSample, _impl_.gps_fix_type_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(HealthSample, _impl_.gps_fix_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 battery_pct = 1;
    {PROTOBUF_FIELD_OFFSET(HealthSample, _impl_.battery_pct_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 link_quality_pct = 2;
    {PROTOBUF_FIELD_OFFSET(HealthSample, _impl_.link_quality_pct_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 gps_fix_type = 3;
    {PROTOBUF_FIELD_OFFSET(HealthSample, _impl_.gps_fix_type_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void HealthSample::Clear() {
// @@protoc_insertion_point(message_clear_start:gundam.v1.HealthSample)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    ::memset(&_impl_.battery_pct_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.gps_fix_type_) -
        reinterpret_cast<char*>(&_impl_.battery_pct_)) + sizeof(_impl_.gps_fix_type_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL HealthSample::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const HealthSample& this_ = static_cast<const HealthSample&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL HealthSample::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const HealthSample& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:gundam.v1.HealthSample)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 battery_pct = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_battery_pct() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_battery_pct(), target);
    }
  }

  // uint32 link_quality_pct = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_link_quality_pct() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          2, this_._internal_link_quality_pct(), target);
    }
  }

  // uint32 gps_fix_type = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_gps_fix_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          3, this_._internal_gps_fix_type(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gundam.v1.HealthSample)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t HealthSample::ByteSizeLong(const MessageLite& base) {
  const HealthSample& this_ = static_cast<const HealthSample&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t HealthSample::ByteSizeLong() const {
  const HealthSample& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:gundam.v1.HealthSample)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // uint32 battery_pct = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_battery_pct() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_battery_pct());
      }
    }
    // uint32 link_quality_pct = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_link_quality_pct() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_link_quality_pct());
      }
    }
    // uint32 gps_fix_type = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_gps_fix_type() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_gps_fix_type());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void HealthSample::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<HealthSample*>(&to_msg);
  auto& from = static_cast<const HealthSample&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:gundam.v1.HealthSample)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_battery_pct() != 0) {
        _this->_impl_.battery_pct_ = from._impl_.battery_pct_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_link_quality_pct() != 0) {
        _this->_impl_.link_quality_pct_ = from._impl_.link_quality_pct_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_gps_fix_type() != 0) {
        _this->_impl_.gps_fix_type_ = from._impl_.gps_fix_type_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void HealthSample::CopyFrom(const HealthSample& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:gundam.v1.HealthSample)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void HealthSample::InternalSwap(HealthSample* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HealthSample, _impl_.gps_fix_type_)
      + sizeof(HealthSample::_impl_.gps_fix_type_)
      - PROTOBUF_FIELD_OFFSET(HealthSample, _impl_.battery_pct_)>(
          reinterpret_cast<char*>(&_impl_.battery_pct_),
          reinterpret_cast<char*>(&other->_impl_.battery_pct_));
}

::google::protobuf::Metadata HealthSample::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MissionUpdate::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<MissionUpdate>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MissionUpdate, _impl_._has_bits_);
};

MissionUpdate::MissionUpdate(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MissionUpdate_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gundam.v1.MissionUpdate)
}
MissionUpdate::MissionUpdate(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MissionUpdate& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MissionUpdate_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE MissionUpdate::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void MissionUpdate::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, state_),
           0,
           offsetof(Impl_, reason_) -
               offsetof(Impl_, state_) +
               sizeof(Impl_::reason_));
}
MissionUpdate::~MissionUpdate() {
  // @@protoc_insertion_point(destructor:gundam.v1.MissionUpdate)
  SharedDtor(*this);
}
inline void MissionUpdate::SharedDtor(MessageLite& self) {
  MissionUpdate& this_ = static_cast<MissionUpdate&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL MissionUpdate::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) MissionUpdate(arena);
}
constexpr auto MissionUpdate::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(MissionUpdate),
                                            alignof(MissionUpdate));
}
constexpr auto MissionUpdate::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MissionUpdate_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &MissionUpdate::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MissionUpdate>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MissionUpdate::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MissionUpdate>(), &MissionUpdate::ByteSizeLong,
              &MissionUpdate::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MissionUpdate, _impl_._cached_size_),
          false,
      },
      &MissionUpdate::kDescriptorMethods,
      &descriptor_table_libs_2fproto_2fdevice_5fevent_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull MissionUpdate_class_data_ =
        MissionUpdate::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
MissionUpdate::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&MissionUpdate_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MissionUpdate_class_data_.tc_table);
  return MissionUpdate_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
MissionUpdate::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MissionUpdate, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    MissionUpdate_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::gundam::v1::MissionUpdate>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .gundam.v1.MissionReason reason = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MissionUpdate, _impl_.reason_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(MissionUpdate, _impl_.reason_)}},
    // .gundam.v1.MissionState state = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MissionUpdate, _impl_.state_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(MissionUpdate, _impl_.state_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .gundam.v1.MissionState state = 1;
    {PROTOBUF_FIELD_OFFSET(MissionUpdate, _impl_.state_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // .gundam.v1.MissionReason reason = 2;
    {PROTOBUF_FIELD_OFFSET(MissionUpdate, _impl_.reason_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void MissionUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:gundam.v1.MissionUpdate)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    ::memset(&_impl_.state_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.reason_) -
        reinterpret_cast<char*>(&_impl_.state_)) + sizeof(_impl_.reason_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL MissionUpdate::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const MissionUpdate& this_ = static_cast<const MissionUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL MissionUpdate::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const MissionUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:gundam.v1.MissionUpdate)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .gundam.v1.MissionState state = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_state() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_state(), target);
    }
  }

  // .gundam.v1.MissionReason reason = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_reason() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          2, this_._internal_reason(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gundam.v1.MissionUpdate)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MissionUpdate::ByteSizeLong(const MessageLite& base) {
  const MissionUpdate& this_ = static_cast<const MissionUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t MissionUpdate::ByteSizeLong() const {
  const MissionUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:gundam.v1.MissionUpdate)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // .gundam.v1.MissionState state = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_state() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_state());
      }
    }
    // .gundam.v1.MissionReason reason = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_reason() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_reason());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void MissionUpdate::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<MissionUpdate*>(&to_msg);
  auto& from = static_cast<const MissionUpdate&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:gundam.v1.MissionUpdate)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_state() != 0) {
        _this->_impl_.state_ = from._impl_.state_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_reason() != 0) {
        _this->_impl_.reason_ = from._impl_.reason_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void MissionUpdate::CopyFrom(const MissionUpdate& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:gundam.v1.MissionUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MissionUpdate::InternalSwap(MissionUpdate* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MissionUpdate, _impl_.reason_)
      + sizeof(MissionUpdate::_impl_.reason_)
      - PROTOBUF_FIELD_OFFSET(MissionUpdate, _impl_.state_)>(
          reinterpret_cast<char*>(&_impl_.state_),
          reinterpret_cast<char*>(&other->_impl_.state_));
}

::google::protobuf::Metadata MissionUpdate::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DeviceEvent::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<DeviceEvent>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(DeviceEvent, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::gundam::v1::DeviceEvent, _impl_._oneof_case_);
};

void DeviceEvent::set_allocated_position_sample(::gundam::v1::PositionSample* PROTOBUF_NULLABLE position_sample) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (position_sample) {
    ::google::protobuf::Arena* submessage_arena = position_sample->GetArena();
    if (message_arena != submessage_arena) {
      position_sample = ::google::protobuf::internal::GetOwnedMessage(message_arena, position_sample, submessage_arena);
    }
    set_has_position_sample();
    _impl_.payload_.position_sample_ = position_sample;
  }
  // @@protoc_insertion_point(field_set_allocated:gundam.v1.DeviceEvent.position_sample)
}
void DeviceEvent::set_allocated_health_sample(::gundam::v1::HealthSample* PROTOBUF_NULLABLE health_sample) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (health_sample) {
    ::google::protobuf::Arena* submessage_arena = health_sample->GetArena();
    if (message_arena != submessage_arena) {
      health_sample = ::google::protobuf::internal::GetOwnedMessage(message_arena, health_sample, submessage_arena);
    }
    set_has_health_sample();
    _impl_.payload_.health_sample_ = health_sample;
  }
  // @@protoc_insertion_point(field_set_allocated:gundam.v1.DeviceEvent.health_sample)
}
void DeviceEvent::set_allocated_mission_update(::gundam::v1::MissionUpdate* PROTOBUF_NULLABLE mission_update) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (mission_update) {
    ::google::protobuf::Arena* submessage_arena = mission_update->GetArena();
    if (message_arena != submessage_arena) {
      mission_update = ::google::protobuf::internal::GetOwnedMessage(message_arena, mission_update, submessage_arena);
    }
    set_has_mission_update();
    _impl_.payload_.mission_update_ = mission_update;
  }
  // @@protoc_insertion_point(field_set_allocated:gundam.v1.DeviceEvent.mission_update)
}
DeviceEvent::DeviceEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, DeviceEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gundam.v1.DeviceEvent)
}
PROTOBUF_NDEBUG_INLINE DeviceEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::gundam::v1::DeviceEvent& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        payload_{},
        _oneof_case_{from._oneof_case_[0]} {}

DeviceEvent::DeviceEvent(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const DeviceEvent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, DeviceEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DeviceEvent* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, event_id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, event_id_),
           offsetof(Impl_, payload_version_) -
               offsetof(Impl_, event_id_) +
               sizeof(Impl_::payload_version_));
  switch (payload_case()) {
    case PAYLOAD_NOT_SET:
      break;
      case kPositionSample:
        _impl_.payload_.position_sample_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.position_sample_);
        break;
      case kHealthSample:
        _impl_.payload_.health_sample_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.health_sample_);
        break;
      case kMissionUpdate:
        _impl_.payload_.mission_update_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.mission_update_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:gundam.v1.DeviceEvent)
}
PROTOBUF_NDEBUG_INLINE DeviceEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        payload_{},
        _oneof_case_{} {}

inline void DeviceEvent::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, event_id_),
           0,
           offsetof(Impl_, payload_version_) -
               offsetof(Impl_, event_id_) +
               sizeof(Impl_::payload_version_));
}
DeviceEvent::~DeviceEvent() {
  // @@protoc_insertion_point(destructor:gundam.v1.DeviceEvent)
  SharedDtor(*this);
}
inline void DeviceEvent::SharedDtor(MessageLite& self) {
  DeviceEvent& this_ = static_cast<DeviceEvent&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_payload()) {
    this_.clear_payload();
  }
  this_._impl_.~Impl_();
}

void DeviceEvent::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:gundam.v1.DeviceEvent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (payload_case()) {
    case kPositionSample: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.position_sample_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.position_sample_);
      }
      break;
    }
    case kHealthSample: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.health_sample_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.health_sample_);
      }
      break;
    }
    case kMissionUpdate: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.mission_update_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.mission_update_);
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


inline void* PROTOBUF_NONNULL DeviceEvent::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) DeviceEvent(arena);
}
constexpr auto DeviceEvent::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(DeviceEvent),
                                            alignof(DeviceEvent));
}
constexpr auto DeviceEvent::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_DeviceEvent_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &DeviceEvent::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<DeviceEvent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &DeviceEvent::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<DeviceEvent>(), &DeviceEvent::ByteSizeLong,
              &DeviceEvent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(DeviceEvent, _impl_._cached_size_),
          false,
      },
      &DeviceEvent::kDescriptorMethods,
      &descriptor_table_libs_2fproto_2fdevice_5fevent_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull DeviceEvent_class_data_ =
        DeviceEvent::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
DeviceEvent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&DeviceEvent_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(DeviceEvent_class_data_.tc_table);
  return DeviceEvent_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 3, 0, 2>
DeviceEvent::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(DeviceEvent, _impl_._has_bits_),
    0, // no _extensions_
    12, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294963680,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    DeviceEvent_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::gundam::v1::DeviceEvent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 event_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(DeviceEvent, _impl_.event_id_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(DeviceEvent, _impl_.event_id_)}},
    // uint64 device_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(DeviceEvent, _impl_.device_id_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(DeviceEvent, _impl_.device_id_)}},
    // uint64 timestamp_unix_ms = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(DeviceEvent, _impl_.timestamp_unix_ms_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(DeviceEvent, _impl_.timestamp_unix_ms_)}},
    // .gundam.v1.EventType type = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DeviceEvent, _impl_.type_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(DeviceEvent, _impl_.type_)}},
    // uint32 payload_version = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DeviceEvent, _impl_.payload_version_), 4>(),
     {40, 4, 0,
      PROTOBUF_FIELD_OFFSET(DeviceEvent, _impl_.payload_version_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 event_id = 1;
    {PROTOBUF_FIELD_OFFSET(DeviceEvent, _impl_.event_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 device_id = 2;
    {PROTOBUF_FIELD_OFFSET(DeviceEvent, _impl_.device_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 timestamp_unix_ms = 3;
    {PROTOBUF_FIELD_OFFSET(DeviceEvent, _impl_.timestamp_unix_ms_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // .gundam.v1.EventType type = 4;
    {PROTOBUF_FIELD_OFFSET(DeviceEvent, _impl_.type_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // uint32 payload_version = 5;
    {PROTOBUF_FIELD_OFFSET(DeviceEvent, _impl_.payload_version_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // .gundam.v1.PositionSample position_sample = 10;
    {PROTOBUF_FIELD_OFFSET(DeviceEvent, _impl_.payload_.position_sample_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .gundam.v1.HealthSample health_sample = 11;
    {PROTOBUF_FIELD_OFFSET(DeviceEvent, _impl_.payload_.health_sample_), _Internal::kOneofCaseOffset + 0, 1, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .gundam.v1.MissionUpdate mission_update = 12;
    {PROTOBUF_FIELD_OFFSET(DeviceEvent, _impl_.payload_.mission_update_), _Internal::kOneofCaseOffset + 0, 2, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::gundam::v1::PositionSample>()},
      {::_pbi::TcParser::GetTable<::gundam::v1::HealthSample>()},
      {::_pbi::TcParser::GetTable<::gundam::v1::MissionUpdate>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void DeviceEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:gundam.v1.DeviceEvent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    ::memset(&_impl_.event_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.payload_version_) -
        reinterpret_cast<char*>(&_impl_.event_id_)) + sizeof(_impl_.payload_version_));
  }
  clear_payload();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL DeviceEvent::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const DeviceEvent& this_ = static_cast<const DeviceEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL DeviceEvent::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const DeviceEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:gundam.v1.DeviceEvent)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint64 event_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_event_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          1, this_._internal_event_id(), target);
    }
  }

  // uint64 device_id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_device_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          2, this_._internal_device_id(), target);
    }
  }

  // uint64 timestamp_unix_ms = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_timestamp_unix_ms() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          3, this_._internal_timestamp_unix_ms(), target);
    }
  }

  // .gundam.v1.EventType type = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          4, this_._internal_type(), target);
    }
  }

  // uint32 payload_version = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_payload_version() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          5, this_._internal_payload_version(), target);
    }
  }

  switch (this_.payload_case()) {
    case kPositionSample: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          10, *this_._impl_.payload_.position_sample_, this_._impl_.payload_.position_sample_->GetCachedSize(), target,
          stream);
      break;
    }
    case kHealthSample: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          11, *this_._impl_.payload_.health_sample_, this_._impl_.payload_.health_sample_->GetCachedSize(), target,
          stream);
      break;
    }
    case kMissionUpdate: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          12, *this_._impl_.payload_.mission_update_, this_._impl_.payload_.mission_update_->GetCachedSize(), target,
          stream);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gundam.v1.DeviceEvent)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t DeviceEvent::ByteSizeLong(const MessageLite& base) {
  const DeviceEvent& this_ = static_cast<const DeviceEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t DeviceEvent::ByteSizeLong() const {
  const DeviceEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:gundam.v1.DeviceEvent)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // uint64 event_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_event_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_event_id());
      }
    }
    // uint64 device_id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_device_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_device_id());
      }
    }
    // uint64 timestamp_unix_ms = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_timestamp_unix_ms() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_timestamp_unix_ms());
      }
    }
    // .gundam.v1.EventType type = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
      }
    }
    // uint32 payload_version = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_payload_version() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_payload_version());
      }
    }
  }
  switch (this_.payload_case()) {
    // .gundam.v1.PositionSample position_sample = 10;
    case kPositionSample: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.position_sample_);
      break;
    }
    // .gundam.v1.HealthSample health_sample = 11;
    case kHealthSample: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.health_sample_);
      break;
    }
    // .gundam.v1.MissionUpdate mission_update = 12;
    case kMissionUpdate: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.mission_update_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void DeviceEvent::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<DeviceEvent*>(&to_msg);
  auto& from = static_cast<const DeviceEvent&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:gundam.v1.DeviceEvent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_event_id() != 0) {
        _this->_impl_.event_id_ = from._impl_.event_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_device_id() != 0) {
        _this->_impl_.device_id_ = from._impl_.device_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_timestamp_unix_ms() != 0) {
        _this->_impl_.timestamp_unix_ms_ = from._impl_.timestamp_unix_ms_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_type() != 0) {
        _this->_impl_.type_ = from._impl_.type_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_payload_version() != 0) {
        _this->_impl_.payload_version_ = from._impl_.payload_version_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case =
          from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_payload();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kPositionSample: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.position_sample_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.position_sample_);
        } else {
          _this->_impl_.payload_.position_sample_->MergeFrom(*from._impl_.payload_.position_sample_);
        }
        break;
      }
      case kHealthSample: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.health_sample_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.health_sample_);
        } else {
          _this->_impl_.payload_.health_sample_->MergeFrom(*from._impl_.payload_.health_sample_);
        }
        break;
      }
      case kMissionUpdate: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.mission_update_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.mission_update_);
        } else {
          _this->_impl_.payload_.mission_update_->MergeFrom(*from._impl_.payload_.mission_update_);
        }
        break;
      }
      case PAYLOAD_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void DeviceEvent::CopyFrom(const DeviceEvent& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:gundam.v1.DeviceEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DeviceEvent::InternalSwap(DeviceEvent* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DeviceEvent, _impl_.payload_version_)
      + sizeof(DeviceEvent::_impl_.payload_version_)
      - PROTOBUF_FIELD_OFFSET(DeviceEvent, _impl_.event_id_)>(
          reinterpret_cast<char*>(&_impl_.event_id_),
          reinterpret_cast<char*>(&other->_impl_.event_id_));
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata DeviceEvent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace gundam
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_libs_2fproto_2fdevice_5fevent_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
