networks:
  edge-net:
    name: edge-net

services:
  postgres:
    image: telemetry/postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - edge-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - edge-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s


  stream-consumer:
    image: telemetry/stream-consumer:latest
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_STREAM: ${REDIS_STREAM}
      REDIS_CONSUMER: ${REDIS_CONSUMER}
      REDIS_GROUP: ${REDIS_GROUP}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

    networks:
      - edge-net

  web-api:
    image: telemetry/web-api:latest
    command: ["npm", "start"]
    working_dir: /app/apps/web-api
    environment:
      API_PORT: ${API_PORT}
      UI_HOST: localhost
      UI_PORT: ${UI_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - edge-net

  web-ui:
    image: telemetry/web-ui:latest
    environment:
      API_PORT: ${API_PORT}
    ports:
      - "${UI_PORT}:80"
    depends_on:
      web-api:
        condition: service_started
    networks:
      - edge-net


volumes:
  postgres_data:
  redis_data:
